name: Github issue -> Notion card
on:
  workflow_dispatch:
  issues: 
    types: [opened, deleted, closed]
jobs:
  issue:
    name: "Issue to Notion"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl 'https://api.notion.com/v1/pages' \
          -H 'Authorization: Bearer '"$NOTION_TOKEN"'' \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2021-08-16" \
          --data '{"parent":{"type":"database_id","database_id":"29876f9a9b864ca39a984f42e17fd345"},"icon":{"type":"emoji","emoji":"🐛"},"properties":{"Name":{"type":"title","title":[{"type":"text","text":{"content":"'"$TITLE"'"}}]},"Assigned":{"people":[{"object":"user","id":"f6cbb362-4908-4138-9ef0-434003d9a9f8"}]},"Status":{"select":{"name":"Current Sprint"}},"Type":{"multi_select":[{"name":"bug"}]}}}'
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          ACTION: ${{ github.event.issue.action }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          TITLE: ${{ github.event.issue.title }}
        shell: bash
