name: Github issue -> Notion card
on:
  workflow_dispatch:
  issues:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Notion Script
        run: ./.github/scripts/notion.sh
        shell: bash
