name: Github issue -> Notion card
on:
  workflow_dispatch:
  issues:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Notion Script
      - uses: actions/checkout@v2
      - run: ./.github/scripts/notion.sh
        shell: bash
